# Generated by Django 2.2 on 2022-12-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=120)),
                ('tabela_preco', models.DecimalField(decimal_places=2, max_digits=20)),
                ('multiplo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
