# Generated by Django 2.2 on 2022-12-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0003_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tabela_preco',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço Unitário'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('data_emissao', models.DateField(auto_now=True)),
                ('info_adicionais', models.CharField(blank=True, max_length=500, null=True, verbose_name='Informaçõs Adicionais')),
                ('condicao_pagamento', models.CharField(max_length=120)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('cliente_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_api.Cliente', verbose_name='Razão Social')),
            ],
        ),
    ]
