# Generated by Django 2.2 on 2022-12-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0004_auto_20221221_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
