# Generated by Django 2.2 on 2022-12-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0006_auto_20221221_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_api.Pedido'),
        ),
    ]
